version: '3.3'
services:
  microweber:
    image: microweber/microweber:php7.1-fpm
    volumes:
      - php-socket:/var/run/php/
      - microweber:/usr/src/microweber
      - ./config:/usr/src/microweber/config
      - ./userfiles:/usr/src/microweber/userfiles
    environment:
      - DB_USER=microweber
      - DB_PASS=microweber
      - DB_NAME=microweber
      - DB_ENGINE=pgsql
      - DB_HOST=db
      - DB_PREFIX=mw_
      - EMAIL=admin@admin.com
      - USER=admin
      - PASSWORD=password
      - TEMPLATE=liteness
    depends_on:
      - db
    restart: on-failure:10
  smtp:
    image: namshi/smtp
    restart: on-failure:10   
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=microweber
      - POSTGRES_PASSWORD=microweber
      - POSTGRES_DB=microweber
    restart: on-failure:10
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - microweber:/usr/src/microweber
      - php-socket:/var/run/php/
      - ./config:/usr/src/microweber/config
      - ./userfiles:/usr/src/microweber/userfiles
    links:
      - microweber
    restart: on-failure:10
  redis:
    image: redis:4-alpine
    restart: on-failure:10
  #caddy:
  #  image: abiosoft/caddy
  #  ports:
  #    - 80:80
  #    - 443:443
  # volumes:
  #    - "{{ volume_path }}/Caddyfile:/etc/Caddyfile"
  #    - "{{ volume_path }}/caddy:/root/.caddy"
  #  restart: always
  #  links:
  #    - kek

volumes:
  microweber:
  php-socket:
    driver_opts:
      type: tmpfs
      device: tmpfs
